kind: 'CDN'
version: '1'
metadata:
  envTypes: ["rde", "dev"]
data:
  originSelectors:
    rules:
      - name: fr-token-replace
        when: { 
          allOf: [
            { reqProperty: tier, equals: publish },
            #{ reqProperty: path, like: /content/b2c/fr/fr* },
            { reqProperty: forwardedDomain, equals: b2cw-test-live-fr.msccruises.com },
            { reqHeader: X-EdgeFunction-Key, doesNotEqual: a8f3b9e2c4d6f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6 }
          ]
        }
        action:
          type: selectAemOrigin
          originName: compute-token-replace
          skipCache: false
      - name: fr-graphql-token-replace
        when: {
          allOf: [
            { reqProperty: tier, equals: publish },
            { reqProperty: forwardedDomain, equals: b2cw-test-live-fr.msccruises.com },
            { reqHeader: X-EdgeFunction-Key, doesNotEqual: "a8f3b9e2c4d6f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6" },
            { reqProperty: path, matches: "^/graphql/execute\\.json/b2c-website-foundation/" },
            { reqProperty: path, like: "*locale%3Dfr_FR*" }
          ]
        }
        action:
          type: selectAemOrigin
          originName: compute-token-replace
          skipCache: false