kind: 'CDN'
version: '1'
metadata:
  envTypes: ["rde"]
data:
  originSelectors:
    rules:
      - name: fr-token-replace
        when: { 
          allOf: [
            { reqProperty: tier, equals: publish },
            { reqProperty: path, like: /content/b2c/fr/fr* },
            { reqHeader: X-EdgeFunction-Key, doesNotEqual: a8f3b9e2c4d6f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6 }
          ]
        }
        action:
          type: selectAemOrigin
          originName: compute-token-replace
          skipCache: false
