kind: "Compute"
version: "1"
metadata:
  envTypes: ["rde"]
data:
  services:
    - name: token-replace
  # Uncomment to enable secrets
  # secrets:
  #   - key: API_TOKEN
  #     value: ${{ API_TOKEN_SECRET }}
