kind: "Compute"
version: "1"
metadata:
  envTypes: ["rde"]
data:
  services:
    - name: token-replace
  origins:
    - name: aem-publish
      # This is the AEM publish backend host (not the Fastly frontend).
      # For your env, use the adobeaemcloud.net host:
      domain: publish-p126355-e1378027.adobeaemcloud.net

  # Uncomment to enable secrets
  # secrets:
  #   - key: API_TOKEN
  #     value: ${{ API_TOKEN_SECRET }}
